"""Add wallet_address to User model

Revision ID: 26951bb70a8a
Revises: 7206def6f115
Create Date: 2024-12-28 22:54:45.338873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26951bb70a8a'
down_revision: Union[str, None] = '7206def6f115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wallet_address', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'user', ['wallet_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'wallet_address')
    # ### end Alembic commands ###
