"""add_col_to_inves

Revision ID: 463a02f1283c
Revises: ae6d6e75523d
Create Date: 2024-09-12 11:04:33.670589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463a02f1283c'
down_revision = 'ae6d6e75523d'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment', sa.Column('request_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment', 'request_date')

    # ### end Alembic commands ###
