"""Add referral_bonus column to User model

Revision ID: 5f2df8666ee5
Revises: cf9707f33ded
Create Date: 2024-09-21 16:33:12.300904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2df8666ee5'
down_revision: Union[str, None] = 'cf9707f33ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('referral_bonus', sa.Float(), nullable=True, server_default='0.0'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'referral_bonus')
    # ### end Alembic commands ###

