"""Add ReferralProfit table

Revision ID: 7206def6f115
Revises: 2047479f47e1
Create Date: 2024-12-27 16:14:33.101040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7206def6f115'
down_revision: Union[str, None] = '2047479f47e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_profit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('profit_amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('message', 'seen',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('message', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('message', 'seen',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_table('referral_profit')
    # ### end Alembic commands ###
