"""Initial tables

Revision ID: 9a3be82d92cd
Revises: 
Create Date: 2024-09-16 11:21:55.662172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3be82d92cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the user table
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('username', sa.String(length=80), unique=True, nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('referral_code', sa.String(length=50), unique=True, nullable=True),
        sa.Column('referred_by', sa.Integer(), sa.ForeignKey('user.id'), nullable=True),
    )

    # Create the admin table
    op.create_table(
        'admin',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('username', sa.String(), unique=True, nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('last_date_log', sa.Date(), nullable=False),
    )

    # Create the level table
    op.create_table(
        'level',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('min_active_users', sa.Integer(), nullable=False),
        sa.Column('min_amount', sa.Float(), nullable=False),
        sa.Column('profit_multiplier', sa.Float(), nullable=False),
    )

    # Create the user_transaction table
    op.create_table(
        'user_transaction',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('type_tran',sa.String(),nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('confirmed', sa.Boolean(), default=False),
        sa.Column('confirm_date', sa.DateTime(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.id'), nullable=False),
        sa.Column('admin_id', sa.Integer(), sa.ForeignKey('admin.id'), nullable=False),
        sa.Column('request_date', sa.DateTime(), nullable=False, default=sa.func.now()),
    )

    # Create the investment table
    op.create_table(
        'investment',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.id'), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('start_time', sa.DateTime()),
        sa.Column('profit', sa.Float(), nullable=True),
        sa.Column('cycle_length', sa.Integer(), nullable=False, default=30),
        sa.Column('is_confirmed', sa.Boolean(), default=False),
        sa.Column('last_withdraw_time', sa.DateTime(), nullable=True),
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('investment')
    op.drop_table('user_transaction')
    op.drop_table('level')
    op.drop_table('admin')
    op.drop_table('user')
    
    # ### end Alembic commands ###