"""add_col_to_investment\

Revision ID: a43dd452f0d2
Revises: fd64e12dbeb5
Create Date: 2024-09-11 18:30:16.819230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43dd452f0d2'
down_revision = 'fd64e12dbeb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment', sa.Column('last_profit_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment', 'last_profit_date')

    # ### end Alembic commands ###
