"""add_new_col_invs3

Revision ID: d04ffa75b8f3
Revises: 9a2a43e9d144
Create Date: 2024-09-09 00:10:40.890324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04ffa75b8f3'
down_revision = '9a2a43e9d144'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment', sa.Column('profit', sa.DECIMAL(precision=10, scale=5), nullable=True))
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('investment', 'profit')
    # ### end Alembic commands ###
