"""create_new_table

Revision ID: fd64e12dbeb5
Revises: d04ffa75b8f3
Create Date: 2024-09-10 09:36:48.179175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd64e12dbeb5'
down_revision = 'd04ffa75b8f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'rate',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('min_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('min_active_user', sa.BigInteger, nullable=False),
        sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate')
    # ### end Alembic commands ###